project:
  type: manuscript
  output-dir: docs
  render:
    - notebooks/analysis.qmd
    - index.qmd

manuscript:
  article: index.qmd
  notebooks: 
  - notebooks/analysis.qmd

format:
  html:
    page-layout: article
    smooth-scroll: true
    link-external-window: true
    theme:
      - ../../style/switchbox.scss
      - styles/custom.css
    include-after-body: ../../style/switchbox.html

    fig-dpi: 300
    fig-format: png
